import nbformat
from nbconvert.preprocessors import ExecutePreprocessor
from langchain_core.messages import ToolMessage
from pathlib import Path

def code_execution_tool(state: AgentState):
    """
    Takes the code block from the state, appends it to the Jupyter Notebook,
    executes the notebook, and updates the state with the results.
    """
    print("--- EXECUTING IN JUPYTER NOTEBOOK ---")
    
    nb_path = "analysis_notebook.ipynb"
    # Ensure the notebook file exists
    if not Path(nb_path).exists():
        nb = nbformat.v4.new_notebook()
        nbformat.write(nb, nb_path)

    # 1. Get the code from the last message (generated by loader or writer)
    code_to_run = state["messages"][-1].content

    # 2. Append the code as a new cell in the .ipynb file
    with open(nb_path, 'r', encoding='utf-8') as f:
        nb = nbformat.read(f, as_version=4)
    
    new_cell = nbformat.v4.new_code_cell(code_to_run)
    nb.cells.append(new_cell)

    # 3. Execute the Notebook
    # timeout=600 allows for large CSVs to load; kernel_name is usually 'python3'
    ep = ExecutePreprocessor(timeout=600, kernel_name='python3')
    try:
        ep.preprocess(nb, {'metadata': {'path': './'}})
    except Exception as e:
        print(f"Execution Error: {e}")
        # Even if it fails, we want to save the notebook to see the error output

    # 4. Save the updated notebook (now contains the output/logs)
    with open(nb_path, 'w', encoding='utf-8') as f:
        nbformat.write(nb, f)

    # 5. Extract current variables (simplified heuristic)
    # In a production agent, you'd parse the cell outputs to find variable names
    current_vars = state.get("internal_variables", {})
    if "pd.read_csv" in code_to_run:
        # Simple extraction of the df_name from the generated code block
        var_name = code_to_run.split("=")[0].strip()
        current_vars[var_name] = "DataFrame"

    # 6. Synchronize the state using our previous function
    # This pulls the cell outputs back into the LangGraph state
    updated_notebook_state = update_state(nb_path, current_vars)

    return {
        **state,
        **updated_notebook_state,
        "next_step": "planner", # Always go back to planner to analyze the results
        "messages": state["messages"] + [ToolMessage(
            content="Code executed successfully. Check notebook_cells for output.",
            tool_call_id="exec_1" # You'd generate a real ID in a full system
        )]
    }