import nbformat
from nbconvert.preprocessors import ExecutePreprocessor
from langchain_core.messages import AIMessage
from pathlib import Path
from datetime import datetime

from model import model, AgentState, tools
from updateNBstate import update_state
from langchain_core.tools import tool

def code_execution_tool(state: AgentState):
    """
    Takes the code block from the state, appends it to the Jupyter Notebook,
    executes the notebook, and updates the state with the results.
    """
    print("--- EXECUTING IN JUPYTER NOTEBOOK ---")
    
    nb_dir = Path("backend/notebooks")
    nb_dir.mkdir(parents=True, exist_ok=True)
    
    # Use existing path from state, or create a new unique one
    if state.get("notebook_path"):
        nb_path = Path(state["notebook_path"])
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        nb_path = nb_dir / f"analysis_{timestamp}.ipynb"

    # Ensure the notebook file exists
    if not nb_path.exists():
        nb = nbformat.v4.new_notebook()
        nbformat.write(nb, str(nb_path))

    # 1. Get the code from the last message (generated by loader or writer)
    code_to_run = state["messages"][-1].content

    # 2. Append the code as a new cell in the .ipynb file
    with open(nb_path, 'r', encoding='utf-8') as f:
        nb = nbformat.read(f, as_version=4)
    
    new_cell = nbformat.v4.new_code_cell(code_to_run)
    nb.cells.append(new_cell)

    # 3. Execute the Notebook
    # timeout=600 allows for large CSVs to load; kernel_name is usually 'python3'
    ep = ExecutePreprocessor(timeout=600, kernel_name='python3')
    try:
        ep.preprocess(nb, {'metadata': {'path': './'}})
    except Exception as e:
        print(f"Execution Error: {e}")
        # Even if it fails, we want to save the notebook to see the error output

    # 4. Synchronize the state using our previous function (Passing nb object to capture errors)
    # This pulls the cell outputs back into the LangGraph state before we delete the cell
    current_vars = state.get("internal_variables", {})
    updated_notebook_state = update_state(str(nb_path), current_vars, nb=nb)

    # 5. Check for errors in the last execution to give better feedback to the planner
    error_detected = False
    if updated_notebook_state.get("notebook_cells"):
        last_cell = updated_notebook_state["notebook_cells"][-1]
        for output in last_cell.get("outputs", []):
            if output.get("output_type") == "error":
                error_detected = True
                break

    # 6. Auto-Cleanup: Remove any cells that produced an error from the notebook file
    nb.cells = [
        cell for cell in nb.cells 
        if not any(out.get("output_type") == "error" for out in cell.get("outputs", []))
    ]

    # 7. Save the notebook (now contains the output/logs of successful cells only)
    abs_nb_path = Path(nb_path).absolute()
    with open(nb_path, 'w', encoding='utf-8') as f:
        nbformat.write(nb, f)
    
    if error_detected:
        print(f"--- FAILURE DETECTED. Erroneous cell removed. Notebook saved to: {abs_nb_path} ---")
    else:
        print(f"--- SUCCESS. Notebook saved to: {abs_nb_path} ---")

    feedback = "Code execution failed with a Python error. Erroneous cell has been removed from the notebook file. Please review the notebook activity and fix the code." if error_detected else "Code executed successfully. Check notebook_cells for output."

    return {
        **state,
        **updated_notebook_state,
        "notebook_path": str(nb_path),
        "next_step": "planner", # Always go back to planner to analyze the results
        "messages": state["messages"] + [AIMessage(content=feedback)]
    }